# Generated by Django 4.1.4 on 2022-12-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("pic", models.ImageField(upload_to="pictures/")),
                ("directions", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("pic", models.ImageField(upload_to="pictures/")),
                ("directions", models.CharField(max_length=250)),
                ("building", models.ManyToManyField(to="map.building")),
            ],
        ),
    ]
