# Generated by Django 4.1.4 on 2022-12-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="room", name="directions",),
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("directions", models.CharField(max_length=250)),
                ("pic", models.ImageField(upload_to="pictures/")),
                (
                    "destination",
                    models.ManyToManyField(
                        related_name="destination_location", to="map.room"
                    ),
                ),
                (
                    "source",
                    models.ManyToManyField(
                        related_name="source_location", to="map.room"
                    ),
                ),
            ],
        ),
    ]
