# Generated by Django 4.1.4 on 2022-12-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0002_remove_room_directions_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="pic",
            field=models.ImageField(blank=True, upload_to="pictures/"),
        ),
        migrations.AlterField(
            model_name="direction",
            name="pic",
            field=models.ImageField(blank=True, upload_to="pictures/"),
        ),
        migrations.AlterField(
            model_name="room",
            name="pic",
            field=models.ImageField(blank=True, upload_to="pictures/"),
        ),
    ]
