# Generated by Django 4.1.4 on 2022-12-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0003_alter_building_pic_alter_direction_pic_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="building", name="directions",),
    ]
