# Generated by Django 4.1.4 on 2022-12-12 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0004_remove_building_directions"),
    ]

    operations = [
        migrations.RemoveField(model_name="direction", name="destination",),
        migrations.RemoveField(model_name="direction", name="source",),
        migrations.RemoveField(model_name="room", name="building",),
        migrations.AddField(
            model_name="direction",
            name="destination",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination_location",
                to="map.room",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="direction",
            name="source",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_location",
                to="map.room",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="building",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="map.building",
            ),
            preserve_default=False,
        ),
    ]
