# Generated by Django 4.1.4 on 2022-12-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0006_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="accessible",
            field=models.BooleanField(default=True),
        ),
    ]
