# Generated by Django 4.1.4 on 2022-12-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0007_room_accessible"),
    ]

    operations = [
        migrations.CreateModel(
            name="Other_loc",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("pic", models.ImageField(blank=True, upload_to="pictures/")),
                ("accessible", models.BooleanField(default=True)),
            ],
        ),
    ]
