# Generated by Django 4.1.4 on 2022-12-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0008_other_loc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location_Access",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=50)),
                ("location", models.ManyToManyField(to="map.room")),
            ],
        ),
    ]
