# Generated by Django 4.1.4 on 2022-12-16 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0009_location_access"),
    ]

    operations = [
        migrations.RenameField(
            model_name="direction", old_name="pic", new_name="directions_pic",
        ),
        migrations.RemoveField(model_name="direction", name="directions",),
    ]
